from django.conf.urls import url

from .views import (
    LoginView,
    ProfileView,
    InstructorView,
    TicketListView,
    TicketDetailView,
    TrainingListView,
    TrainingUpdateView,
    TrainingDocumentListView,
    TrainingDocumentDeleteView,
    ParticipantSelectTrainingView,
    InstructorAcceptParticipantView,
    InstructorAcceptFistParticipantView,
    InstructorAcceptSecondParticipantView,
    ParticipantAcceptTrainingView,
    ParticipantTrainingAcceptedList,
    user_logout
)

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', user_logout, name='logout'),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^instructor/$', InstructorView.as_view(), name='instructor'),
    url(r'^tickets/$', TicketListView.as_view(), name='tickets'),
    url(r'^tickets/(?P<pk>[0-9]+)$', TicketDetailView.as_view(), name='ticket_detail'),

    url(r'^participant/trainings/select/$', ParticipantSelectTrainingView.as_view(), name='training_select'),
    url(r'^participant/trainings/accept/$', ParticipantAcceptTrainingView.as_view(), name='training_accept'),
    url(r'^instructor/trainings/$', TrainingListView.as_view(), name='trainings'),
    url(r'^instructor/trainings/(?P<pk>[0-9]+)$', TrainingUpdateView.as_view(), name='training_update'),
    url(r'^instructor/trainings/(?P<pk>[0-9]+)/documents/$',
        TrainingDocumentListView.as_view(),
        name='training_documents'),
    url(r'^instructor/trainings/documents/delete/(?P<pk>[0-9]+)$',
        TrainingDocumentDeleteView.as_view(),
        name='delete_documents'),
    url(r'^instructor/trainings/(?P<pk>[0-9]+)/accept/$',
        InstructorAcceptParticipantView.as_view(),
        name='participant_accept'),
    url(r'^instructor/trainings/(?P<pk>[0-9]+)/accept/first/$',
        InstructorAcceptFistParticipantView.as_view(),
        name='participant_accept_first'),
    url(r'^instructor/trainings/(?P<pk>[0-9]+)/accept/second/$',
        InstructorAcceptSecondParticipantView.as_view(),
        name='participant_accept_second'),
    url(r'^instructor/trainings/(?P<pk>[0-9]+)/participants/accepted/$',
        ParticipantTrainingAcceptedList.as_view(),
        name='accepted_participants'),
]
