# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170301_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registered_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
