# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_registered_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='registered_ip',
        ),
    ]
