# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_registered_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, max_length=100, verbose_name='kurum/üniversite'),
        ),
    ]
