# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 11:44
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='format: +905306602321', max_length=128, verbose_name='telefon'),
        ),
    ]
