# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.SmallIntegerField(choices=[(0, 'Süperuser'), (1, 'Moderatör'), (2, 'Eğitmen'), (3, 'Katılımcı')], default=3),
        ),
    ]
