# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20170303_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instructor/', validators=[main.utils.validate_avatar_dimensions]),
        ),
    ]
