# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hacktrick', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertraining',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trainings', related_query_name='user_training', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingdocument',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', related_query_name='document', to='hacktrick.Training'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', related_query_name='ticket_comment', to='hacktrick.Ticket'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', related_query_name='ticket_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', related_query_name='ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speaker',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', related_query_name='speaker', to='hacktrick.ConferenceSlot'),
        ),
    ]
