# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hacktrick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertraining',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trainings', related_query_name='user_training', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingdocument',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', related_query_name='document', to='hacktrick.Training'),
        ),
        migrations.AddField(
            model_name='training',
            name='instructor',
            field=models.ManyToManyField(related_name='trainings', related_query_name='training', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', related_query_name='ticket_comment', to='hacktrick.Ticket'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', related_query_name='ticket_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', related_query_name='ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speak',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaks', related_query_name='speak', to='hacktrick.ConferenceSlot'),
        ),
        migrations.AddField(
            model_name='speak',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', related_query_name='speak', to='hacktrick.Speaker'),
        ),
    ]
