# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0002_auto_20170306_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='speak',
            name='hall',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
