# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0002_auto_20170301_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'Platin'), (1, 'Altın'), (2, 'Gümüş'), (3, 'Media'), (4, 'Destekleyenler')]),
        ),
    ]
