# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0003_speak_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speak',
            name='hall',
            field=models.CharField(max_length=100, verbose_name='Salon'),
        ),
    ]
