# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0005_remove_faq_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'Platin'), (1, 'Altın'), (2, 'Gümüş'), (3, 'Destekleyenler'), (4, 'Medya'), (5, 'Bronz'), (6, 'Stand')]),
        ),
    ]
