# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0006_auto_20170307_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='website',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
