# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import hacktrick.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0007_sponsor_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=models.ImageField(help_text='160x160', upload_to='speaker/', validators=[hacktrick.utils.validate_speaker_image_dimensions], verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(help_text='370x190', upload_to='sponsor/', validators=[hacktrick.utils.validate_sponsor_image_dimensions]),
        ),
    ]
