# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import hacktrick.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0008_auto_20170307_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(help_text='372x191', upload_to='sponsor/', validators=[hacktrick.utils.validate_sponsor_image_dimensions]),
        ),
    ]
