# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0009_auto_20170307_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ('date',)},
        ),
    ]
