# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 12:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0012_ticket_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='training_note',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Eğitim notu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='date',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
