# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 12:58
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0013_auto_20170308_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about',
            field=ckeditor.fields.RichTextField(verbose_name='Hakkında'),
        ),
    ]
