# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 14:49
from __future__ import unicode_literals

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0016_auto_20170308_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='content',
            field=django_bleach.models.BleachField(),
        ),
    ]
