# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 14:51
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0017_auto_20170308_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
