# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import hacktrick.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0018_auto_20170308_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='cover_image',
            field=models.ImageField(help_text='770×420', upload_to='training/', validators=[hacktrick.utils.validate_training_image_dimensions]),
        ),
    ]
