# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0020_training_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdocument',
            name='document',
        ),
        migrations.AddField(
            model_name='trainingdocument',
            name='document_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
