# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0021_auto_20170308_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdocument',
            name='is_public',
        ),
    ]
