# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0022_remove_trainingdocument_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertraining',
            name='accepted_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accepted_trainings', related_query_name='user_accepted_training', to='hacktrick.Training'),
        ),
    ]
