# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0023_auto_20170309_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertraining',
            name='first_selection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_first_trainings', related_query_name='user_first_training', to='hacktrick.Training'),
        ),
        migrations.AlterField(
            model_name='usertraining',
            name='second_selection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_second_trainings', related_query_name='user_second_training', to='hacktrick.Training'),
        ),
    ]
