# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0024_auto_20170309_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertraining',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_training', related_query_name='user_training', to=settings.AUTH_USER_MODEL),
        ),
    ]
