# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0025_auto_20170309_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='participant_selection',
            field=models.BooleanField(default=False, verbose_name='Öğrenci seçimi'),
        ),
        migrations.AddField(
            model_name='setting',
            name='training_selection',
            field=models.BooleanField(default=False, verbose_name='Eğitim seçimi'),
        ),
    ]
