# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0027_usertraining_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='parpicipant_accept',
            field=models.BooleanField(default=False, verbose_name='Katılımcı onay'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='participant_selection',
            field=models.BooleanField(default=False, verbose_name='Katılımcı seçimi'),
        ),
    ]
