# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 18:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0029_auto_20170310_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CFP',
        ),
        migrations.AddField(
            model_name='setting',
            name='cfp',
            field=ckeditor.fields.RichTextField(default='', verbose_name='CFP'),
            preserve_default=False,
        ),
    ]
