# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0032_auto_20170312_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='title',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
