# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:13
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hacktrick.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0033_mail_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferenceslot',
            options={'verbose_name': 'Konferans Slotu', 'verbose_name_plural': 'Konferans Slotları'},
        ),
        migrations.AlterModelOptions(
            name='contributor',
            options={'verbose_name': 'Katkıda bulunan', 'verbose_name_plural': 'Katkıda bulunanlar'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Soru', 'verbose_name_plural': 'Sıkça Sorulan Sorular'},
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': 'Mail', 'verbose_name_plural': 'Mailler'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Ayarlar', 'verbose_name_plural': 'Ayarlar'},
        ),
        migrations.AlterModelOptions(
            name='speak',
            options={'verbose_name': 'Konuşma', 'verbose_name_plural': 'Konuşmalar'},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'verbose_name': 'Konuşmacı', 'verbose_name_plural': 'Konuşmacılar'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsorlar'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Soru', 'verbose_name_plural': 'Sorular'},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ('date',), 'verbose_name': 'Soru yorumu', 'verbose_name_plural': 'Soru yorumları'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Eğitim', 'verbose_name_plural': 'Eğitimler'},
        ),
        migrations.AlterModelOptions(
            name='trainingdocument',
            options={'verbose_name': 'Eğitim dökümanı', 'verbose_name_plural': 'Eğitim dökümanları'},
        ),
        migrations.AlterModelOptions(
            name='usertraining',
            options={'verbose_name': 'Katılımcı eğitim', 'verbose_name_plural': 'Katılımcı eğitim'},
        ),
        migrations.AddField(
            model_name='contributor',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Durum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conferenceslot',
            name='date',
            field=models.DateField(unique=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='Ad sayad'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='image',
            field=models.ImageField(upload_to='contributor/', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='mission',
            field=models.CharField(max_length=100, verbose_name='Görev'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(verbose_name='Cevap'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=300, verbose_name='Soru'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Kayıt'), (1, 'Eğitim seçimi'), (2, 'Eğitim onayı'), (3, 'Eğitimin güncellenmesi'), (4, 'Eğitime döküman eklenmesi'), (5, 'Bir kullanıcının eğitmen olarak işaretlenmesi'), (6, 'Eğitime kesin kayıt olunması'), (7, 'Ticket açılması'), (8, 'Ticketa cevap verilmesi'), (9, 'Bir kullanıcının herhangi bir eğitime eğitmen olarak atanması'), (10, 'Bir kullanıcının herhangi bir eğitimden eğitmenliğinin kaldırılması')], help_text='İçerik harici kullanıcıya extra bilgiler verilmektedir.', unique=True, verbose_name='Mail seçimi'),
        ),
        migrations.AlterField(
            model_name='speak',
            name='ending_time',
            field=models.TimeField(verbose_name='Bitiş zamanı'),
        ),
        migrations.AlterField(
            model_name='speak',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaks', related_query_name='speak', to='hacktrick.ConferenceSlot', verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='speak',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', related_query_name='speak', to='hacktrick.Speaker', verbose_name='Konuşmacı'),
        ),
        migrations.AlterField(
            model_name='speak',
            name='starting_time',
            field=models.TimeField(verbose_name='Başlangıç zamanı'),
        ),
        migrations.AlterField(
            model_name='speak',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'Platin'), (1, 'Altın'), (2, 'Gümüş'), (3, 'Destekleyenler'), (4, 'Medya'), (5, 'Bronz'), (6, 'Stand')], verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(help_text='372x191', upload_to='sponsor/', validators=[hacktrick.utils.validate_sponsor_image_dimensions], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='website',
            field=models.URLField(verbose_name='Websitesi'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.BooleanField(default=True, verbose_name='Cevaplanabilirlik'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', related_query_name='ticket', to=settings.AUTH_USER_MODEL, verbose_name='Katılımcı'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='comment',
            field=models.TextField(verbose_name='Yorum'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', related_query_name='ticket_comment', to='hacktrick.Ticket', verbose_name='Soru'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', related_query_name='ticket_comment', to=settings.AUTH_USER_MODEL, verbose_name='Katılımcı'),
        ),
        migrations.AlterField(
            model_name='training',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Kontenjan'),
        ),
        migrations.AlterField(
            model_name='training',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='training',
            name='cover_image',
            field=models.ImageField(help_text='770×420', upload_to='training/', validators=[hacktrick.utils.validate_training_image_dimensions], verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.CharField(max_length=20, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='training',
            name='instructor',
            field=models.ManyToManyField(related_name='trainings', related_query_name='training', to='profiles.Instructor', verbose_name='Eğitmen'),
        ),
        migrations.AlterField(
            model_name='training',
            name='reserve_quota',
            field=models.PositiveIntegerField(verbose_name='Ek kontenjan'),
        ),
        migrations.AlterField(
            model_name='training',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='trainingdocument',
            name='document_url',
            field=models.URLField(verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='trainingdocument',
            name='name',
            field=models.CharField(max_length=100, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='trainingdocument',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', related_query_name='document', to='hacktrick.Training', verbose_name='Eğitim'),
        ),
        migrations.AlterField(
            model_name='usertraining',
            name='accepted_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accepted_trainings', related_query_name='user_accepted_training', to='hacktrick.Training', verbose_name='Kabul edilen seçim'),
        ),
        migrations.AlterField(
            model_name='usertraining',
            name='first_selection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_first_trainings', related_query_name='user_first_training', to='hacktrick.Training', verbose_name='İlk seçim'),
        ),
        migrations.AlterField(
            model_name='usertraining',
            name='second_selection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_second_trainings', related_query_name='user_second_training', to='hacktrick.Training', verbose_name='ikinci seçim'),
        ),
        migrations.AlterField(
            model_name='usertraining',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_training', related_query_name='user_training', to=settings.AUTH_USER_MODEL, verbose_name='Katılımcı'),
        ),
    ]
