# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import hacktrick.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0035_auto_20170313_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='image',
            field=models.ImageField(upload_to='contributor/', validators=[hacktrick.utils.validate_contributor_image_dimensions], verbose_name='Resim'),
        ),
    ]
