# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0037_speaker_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='live_broadcast',
            field=models.TextField(blank=True, help_text='Html embed code'),
        ),
    ]
