# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-17 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0038_setting_live_broadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='user',
            field=models.ForeignKey(help_text='Otomatik doldurulur', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', related_query_name='ticket_comment', to=settings.AUTH_USER_MODEL, verbose_name='Katılımcı'),
        ),
    ]
