# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-18 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0039_auto_20180217_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertraining',
            name='accepted_selection',
        ),
        migrations.RemoveField(
            model_name='usertraining',
            name='second_selection',
        ),
        migrations.AddField(
            model_name='usertraining',
            name='accepted_training',
            field=models.BooleanField(default=False, verbose_name='Eğitim Onayı'),
        ),
    ]
