# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-03 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0041_remove_usertraining_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='training',
            name='status',
        ),
    ]
