# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-06 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0043_remove_training_reserve_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='limitless',
            field=models.BooleanField(default=False, verbose_name='Sınırsız Kontenjan'),
            preserve_default=False,
        ),
    ]
