# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-06 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0044_training_limitless'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, verbose_name='Kontenjan'),
        ),
    ]
