# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-06 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0047_bugminer_csaward_demoroom_gameofpwners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugminer',
            name='order',
        ),
        migrations.RemoveField(
            model_name='csaward',
            name='order',
        ),
        migrations.RemoveField(
            model_name='demoroom',
            name='order',
        ),
        migrations.RemoveField(
            model_name='gameofpwners',
            name='order',
        ),
    ]
