# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-06 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0049_usertraining_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertraining',
            name='user_status',
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateTimeField(max_length=20, verbose_name='Tarih'),
        ),
    ]
