# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-06 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0050_auto_20180306_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(max_length=20, verbose_name='Tarih'),
        ),
    ]
