# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-06 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0053_usertraining_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='participant_accept',
        ),
    ]
