# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-06 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0055_auto_20180306_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='finish_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Bitiş Tarihi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(verbose_name='Başlangıç Tarihi'),
        ),
    ]
