# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-08 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0057_auto_20180307_1629'),
        ('hacktrick', '0057_auto_20180307_2027'),
    ]

    operations = [
    ]
