# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-08 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0058_merge_20180308_1225'),
        ('hacktrick', '0058_merge_20180307_2327'),
    ]

    operations = [
    ]
