# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-08 19:19
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0059_merge_20180308_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='accommodation',
            field=ckeditor.fields.RichTextField(default='asdasd', verbose_name='Konaklama'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='contact',
            field=ckeditor.fields.RichTextField(default='asdasd', verbose_name='İletişim'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='user',
            field=models.ForeignKey(help_text='Otomatik doldurulur', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', related_query_name='ticket_comment', to=settings.AUTH_USER_MODEL, verbose_name='Yönetici'),
        ),
    ]
