# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-08 19:27
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0060_auto_20180308_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='transportation',
            field=ckeditor.fields.RichTextField(default='cemil', verbose_name='Ulaşım'),
            preserve_default=False,
        ),
    ]
