# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-09 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0064_setting_speaker_selection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='speaker_selection',
        ),
    ]
