# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-09 23:16
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0067_usertraining_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='agreement_note',
            field=ckeditor.fields.RichTextField(default='cemil', verbose_name='Eğitim kabul sözleşmesi'),
            preserve_default=False,
        ),
    ]
