# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-09 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0068_setting_agreement_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='agreement_note',
        ),
    ]
