# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-10 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacktrick', '0070_setting_agreement_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertraining',
            name='agreement',
        ),
    ]
